Repository UTRS2/utrs, pull requests merged in 2020-06, with the labels that each got.

#183 Validate that appeals can be verified before attempting to verify them
  app/Http/Controllers/AppealController.php
Labels: Priority: Low, bug

#88 Feature/laravel jobs permission checking
  .env.ci
  app/Http/Controllers/AppealController.php
  app/Jobs/GetBlockDetailsJob.php
  app/Jobs/WikiPermission/BaseWikiPermissionJob.php
  app/Jobs/WikiPermission/LoadGlobalPermissionsJob.php
  app/Jobs/WikiPermission/LoadLocalPermissionsJob.php
  app/MwApi/MwApiGetter.php
  app/User.php
  config/wikis.php
  python/wikiactions.py
  tests/Feature/Jobs/WikiPermission/WikiPermissionJobTest.php
Labels: enhancement

#191 Fix and cleanup tooladmin button
  .github/workflows/laravel-tests.yml
  app/Http/Controllers/AppealController.php
  resources/views/appeals/appeal.blade.php
  routes/web.php
  tests/Browser/Appeals/AppealDeferTest.php
Labels: Priority: High, bug

#106 User management & permission management rewrite
  app/Appeal.php
  app/Console/Commands/RemoveDuplicatePermissionsCommand.php
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/AppealController.php
  app/Jobs/WikiPermission/BaseWikiPermissionJob.php
  app/Jobs/WikiPermission/LoadGlobalPermissionsJob.php
  app/Jobs/WikiPermission/LoadLocalPermissionsJob.php
  app/Log.php
  app/MwApi/MwApiUrls.php
  app/Permission.php
  app/Policies/Admin/BanPolicy.php
  app/Policies/Admin/SiteNoticePolicy.php
  app/Policies/Admin/TemplatePolicy.php
  app/Policies/Admin/UserPolicy.php
  app/Policies/AppealPolicy.php
  app/Policies/OldAppealPolicy.php
  app/Providers/AuthServiceProvider.php
  app/User.php
  database/migrations/2020_06_06_212518_remove_permissions_privacy.php
  public/css/app.css
  public/mix-manifest.json
  resources/views/admin/users/view.blade.php
  resources/views/appeals/appeal.blade.php
  resources/views/appeals/appeallist.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
  tests/Browser/Appeals/AppealListTest.php
  tests/Feature/Jobs/WikiPermission/WikiPermissionJobTest.php
Labels: Priority: High, enhancement

#205 Upgrade PHP 7.3, required by mockery/mockery 1.4.0 and further updates
  composer.json
Labels: dependencies

#208 Add documentation to README about setting up mediawiki integration
  readme.md
Labels: documentation

#158 Massive public appeal overhaul
  .github/workflows/laravel-tests.yml
  app/Appeal.php
  app/Http/Controllers/Appeal/PublicAppealController.php
  app/Http/Controllers/Appeal/PublicAppealModifyController.php
  app/Http/Controllers/AppealController.php
  app/Http/Controllers/AppealModifyController.php
  app/Http/Controllers/HomeController.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  app/Jobs/VerifyBlockJob.php
  app/Permission.php
  app/Providers/AppServiceProvider.php
  database/factories/AppealFactory.php
  database/migrations/2020_05_25_150830_remove_privacy.php
  public/css/app.css
  public/mix-manifest.json
  resources/lang/en/appeals.php
  resources/lang/en/generic.php
  resources/lang/en/home.php
  resources/lang/en/validation.php
  resources/lang/qqq/appeals.php
  resources/lang/qqq/generic.php
  resources/lang/qqq/home.php
  resources/views/appeals/fixip.blade.php
  resources/views/appeals/makeappeal/account.blade.php
  resources/views/appeals/makeappeal/hash.blade.php
  resources/views/appeals/makeappeal/ip.blade.php
  resources/views/appeals/public/appeal.blade.php
  resources/views/appeals/public/makeappeal/account.blade.php
  resources/views/appeals/public/makeappeal/hash.blade.php
  resources/views/appeals/public/makeappeal/ip.blade.php
  resources/views/appeals/public/modify.blade.php
  resources/views/appeals/public/verify.blade.php
  resources/views/appeals/publicappeal.blade.php
  resources/views/appeals/verifyaccount.blade.php
  resources/views/components/errors.blade.php
  resources/views/errors/404.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
  tests/Browser/Appeals/AppealCommentsTest.php
  tests/Browser/Appeals/AppealCreateTest.php
  tests/Browser/Appeals/AppealPublicActionsTest.php
Labels: enhancement, tech-debt

#224 Fix UTRS 1 appeal comments not showing up
  resources/views/appeals/oldappeal.blade.php
Labels: bug

#225 Add support for looking up UTRS 1 appeals in quick search
  app/Http/Controllers/AppealController.php
Labels: enhancement

#221 Add appeal list category separation
  app/Http/Controllers/AppealController.php
  public/css/app.css
  public/mix-manifest.json
  resources/views/appeals/appeallist.blade.php
  tests/Browser/Appeals/AppealListTest.php
Labels: enhancement
