Repository UTRS2/utrs, pull requests merged in 2020-10, with the labels that each got.

#317 Fix some issues found with recent log model migrations
  app/Http/Controllers/Admin/UserController.php
  app/Models/LogEntry.php
  app/Models/User.php
  resources/views/components/logs.blade.php
Labels: Priority: High, bug

#319 Patch security issues
  package-lock.json
  package.json
Labels: Priority: High, dependencies, security

#321 Ignore user table wikis column when building appeal list
  app/Http/Controllers/AppealController.php
Labels: bug

#228 Add custom error messages on 401 /appeal/{id} and on 404 /public/appeal/view
  app/Http/Controllers/Appeal/PublicAppealController.php
  app/Http/Controllers/AppealController.php
  public/css/app.css
  public/mix-manifest.json
  resources/lang/en/appeals.php
  resources/lang/en/auth.php
  resources/lang/qqq/appeals.php
  resources/lang/qqq/auth.php
  resources/views/appeals/public/needauth.blade.php
  resources/views/appeals/public/wrongkey.blade.php
  resources/views/home.blade.php
  routes/web.php
Labels: enhancement

#172 Show message when user can't see any appeals
  app/Http/Controllers/AppealController.php
  resources/views/appeals/appeallist.blade.php
Labels: testing
