Repository UTRS2/utrs, pull requests merged in 2020-05, with the labels that each got.

#44 Unbreak appeal creation
  app/Http/Controllers/AppealController.php
  resources/views/appeals/makeappeal/account.blade.php
  resources/views/appeals/makeappeal/ip.blade.php
Labels: Priority: High

#67 Code cleanup
  app/Http/Controllers/AppealController.php
  resources/views/appeals/appeal.blade.php
  routes/web.php
Labels: Priority: Low

#55 Fix public appeal commenting and refreshing
  app/Http/Controllers/AppealController.php
  resources/views/appeals/publicappeal.blade.php
  resources/views/home.blade.php
  routes/web.php
Labels: Priority: High, enhancement

#60 Remove old appeal email #47
  app/Http/Controllers/AppealController.php
  resources/views/appeals/oldappeal.blade.php
Labels: Priority: Low

#66 Show previous appeals
  app/Appeal.php
  app/Http/Controllers/AppealController.php
  public/css/app.css
  public/mix-manifest.json
  resources/views/appeals/appeal.blade.php
Labels: Priority: Medium, enhancement

#93 Form submit
  resources/views/appeals/appeal.blade.php
Labels: bug

#89 Old appeal fixes
  app/Http/Controllers/AppealController.php
  resources/views/appeals/oldappeal.blade.php
Labels: bug

#94 Fix "User talk" button not opening user talk page
  resources/views/appeals/appeal.blade.php
Labels: bug

#86 Cosmetic changes
  resources/views/appeals/appeal.blade.php
  resources/views/appeals/oldappeal.blade.php
  resources/views/appeals/publicappeal.blade.php
Labels: Priority: Low

#102 All the formatting changes
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/AppealController.php
  app/Http/Controllers/AppealModifyController.php
  app/Permission.php
  app/User.php
  resources/views/admin/edittemplate.blade.php
  resources/views/admin/newtemplate.blade.php
  resources/views/admin/tables.blade.php
  resources/views/appeals/appeal.blade.php
  resources/views/appeals/appeallist.blade.php
  resources/views/appeals/ban.blade.php
  resources/views/appeals/custom.blade.php
  resources/views/appeals/deny.blade.php
  resources/views/appeals/fixip.blade.php
  resources/views/appeals/loggedin.blade.php
  resources/views/appeals/makeappeal/account.blade.php
  resources/views/appeals/makeappeal/hash.blade.php
  resources/views/appeals/makeappeal/ip.blade.php
  resources/views/appeals/oldappeal.blade.php
  resources/views/appeals/privacydeny.blade.php
  resources/views/appeals/publicappeal.blade.php
  resources/views/appeals/spam.blade.php
  resources/views/appeals/templates.blade.php
  resources/views/appeals/unverifiedappeal.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
Labels: Cosmetics

#101 CU links line spacing
  resources/views/appeals/appeal.blade.php
Labels: Cosmetics

#91 Fix users not seeing their own comments
  app/Appeal.php
  app/Http/Controllers/AppealController.php
  database/migrations/2020_05_16_174724_migrate_old_blocked_user_comments.php
  resources/views/appeals/appeal.blade.php
  resources/views/appeals/publicappeal.blade.php
Labels: Priority: High, bug

#105 Fix users without permissions
  app/Permission.php
Labels: Priority: High, bug

#87 Allow oversighting bans
  app/Ban.php
  app/Http/Controllers/AdminController.php
  app/Permission.php
  database/migrations/2020_05_16_093800_add_hidden_to_bans.php
  public/css/app.css
  public/mix-manifest.json
  resources/views/admin/tables.blade.php
Labels: Priority: High, enhancement

#33 Verify appeal creator and block existence in a laravel job
  .env.example
  .gitignore
  app/Appeal.php
  app/Http/Controllers/AppealController.php
  app/Jobs/GetBlockDetailsJob.php
  app/Jobs/VerifyBlockJob.php
  app/MwApi/MwApiExtras.php
  app/MwApi/MwApiGetter.php
  app/MwApi/MwApiUrls.php
  app/Rules/SecretEqualsRule.php
  composer.json
  config/queue.php
  config/wikis.php
  database/migrations/2020_05_11_091022_add_verify_token_to_appeals.php
  python/wikiactions.py
  readme.md
  resources/views/appeals/appeal.blade.php
  resources/views/appeals/verifyaccount.blade.php
  routes/web.php
Labels: Priority: High, dependencies

#110 Fix block detail job for blocks without a hidden ip and a wrong username
  app/Jobs/GetBlockDetailsJob.php
Labels: Priority: High, bug

#112 Fix couple of bugs
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/AppealController.php
  database/migrations/2020_05_20_051820_change_column_size_appeal.php
Labels: bug

#111 Browser testing
  .env.ci
  .github/workflows/laravel-tests.yml
  .gitignore
  app/Jobs/GetBlockDetailsJob.php
  app/MwApi/MwApiGetter.php
  app/MwApi/MwApiUrls.php
  app/Permission.php
  composer.json
  config/wikis.php
  database/factories/UserFactory.php
  database/migrations/2019_10_08_102117_create_appeals_cu_tables.php
  database/migrations/2019_10_12_005839_create_logs_table.php
  database/migrations/2020_03_08_041516_modify_logs.php
  public/css/app.css
  public/mix-manifest.json
  resources/views/appeals/makeappeal/account.blade.php
  resources/views/appeals/makeappeal/ip.blade.php
  tests/Browser/Appeals/AppealCreateTest.php
  tests/Browser/Appeals/AppealListTest.php
  tests/Browser/HomePageTest.php
  tests/Browser/Pages/HomePage.php
  tests/Browser/Pages/Page.php
  tests/Browser/console/.gitignore
  tests/Browser/screenshots/.gitignore
  tests/DuskTestCase.php
  tests/Traits/TestHasUsers.php
Labels: testing

#113 Store HSTS max age in config to allow config caching
  app/Http/Middleware/AddHstsHeader.php
  config/app.php
Labels: Priority: Low, bug

#119 Restore pull #64
  app/Http/Controllers/AppealController.php
Labels: bug

#117 Fix loading appeal data for IP range appeals
  app/MwApi/MwApiExtras.php
  app/Utils/IPUtils.php
  tests/Unit/Utils/IPUtilsTest.php
Labels: Priority: High, bug

#125 Fix loading autoblock details
  app/Jobs/GetBlockDetailsJob.php
  app/MwApi/MwApiExtras.php
Labels: Priority: High, bug

#126 Add sanity checks to MwApiExtras, fix global requests with hiddenip=null
  app/Jobs/GetBlockDetailsJob.php
  app/MwApi/MwApiExtras.php
Labels: bug

#127 Add wiki to block list
  resources/views/appeals/appeallist.blade.php
Labels: enhancement

#120 Create custom 500 page
  resources/views/errors/500.blade.php
Labels: Priority: High, enhancement

#134 User ID vs username
  python/wikiactions.py
Labels: Priority: High, bug

#133 Load block details when changing block values
  app/Http/Controllers/AppealModifyController.php
Labels: Priority: High, bug

#148 Add spatie/laravel-backup
  .env.example
  .gitignore
  app/Console/Kernel.php
  composer.json
  config/backup.php
  config/database.php
Labels: Priority: High

#138 Make user info buttons on appeal page point to correct wiki
  app/MwApi/MwApiUrls.php
  config/wikis.php
  resources/views/appeals/appeal.blade.php
Labels: Priority: Medium, bug

#150 Add reverify appeal
  app/Http/Controllers/AppealController.php
  resources/views/appeals/appeal.blade.php
  routes/web.php
Labels: enhancement

#121 Format links in block reasons
  app/Appeal.php
  public/css/app.css
  public/mix-manifest.json
  resources/views/appeals/appeal.blade.php
  resources/views/appeals/appeallist.blade.php
Labels: Priority: Wishlist, enhancement

#149 Allow finding last appeal for user/appeal id
  app/Http/Controllers/AppealController.php
  public/css/app.css
  public/mix-manifest.json
  resources/views/appeals/appeallist.blade.php
  routes/web.php
Labels: enhancement

#159 Add custom 40[34] messages, fix appeal visibility
  app/Http/Controllers/AppealController.php
  resources/views/appeals/privacydeny.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
Labels: bug

#157 Include doctype and lang attribute
  resources/views/layouts/app.blade.php
Labels: enhancement

#160 Make certain fields longer to allow replies and templates longer than 191 chars
  database/migrations/2020_05_25_181741_make_comments_longer.php
Labels: Priority: High, bug

#135 Allow setting status when replying
  app/Appeal.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/AppealController.php
  app/Http/Controllers/AppealModifyController.php
  config/wikis.php
  database/factories/AppealFactory.php
  database/factories/TemplateFactory.php
  database/migrations/2020_05_26_120440_default_status_from_template.php
  public/css/app.css
  public/mix-manifest.json
  resources/sass/_variables.scss
  resources/sass/app.scss
  resources/views/admin/edittemplate.blade.php
  resources/views/admin/newtemplate.blade.php
  resources/views/appeals/appeal.blade.php
  resources/views/appeals/custom.blade.php
  resources/views/appeals/publicappeal.blade.php
  resources/views/appeals/templates.blade.php
  resources/views/components/errors.blade.php
  routes/web.php
  tests/Browser/Appeals/AppealCommentsTest.php
  tests/Traits/TestHasUsers.php
Labels: Priority: High, enhancement

#12 Feature/oauth
  .env.example
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/OauthLoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Controllers/Auth/VerificationController.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  app/OAuth/WikiHmacSha1Signature.php
  app/OAuth/WikiSocialiteProvider.php
  app/OAuth/WikiSocialiteServer.php
  app/Providers/AuthServiceProvider.php
  composer.json
  config/services.php
  python/wikiactions.py
  resources/views/home.blade.php
  routes/web.php
Labels: Priority: Medium

#165 Fix some users not being able to view some appeals
  app/Http/Controllers/AppealController.php
Labels: Priority: High, bug

#122 Force comment reason when deferring to CU
  app/Appeal.php
  app/Http/Controllers/AppealController.php
  app/Log.php
  database/migrations/2020_05_29_174632_update_log_protection_values.php
  public/css/app.css
  public/mix-manifest.json
  resources/views/appeals/appeal.blade.php
  resources/views/appeals/publicappeal.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: Priority: High, enhancement

#173 Use taavi/laravel-socialite-mediawiki for OAuth
  app/Http/Controllers/Auth/OauthLoginController.php
  app/OAuth/WikiHmacSha1Signature.php
  app/OAuth/WikiSocialiteProvider.php
  app/OAuth/WikiSocialiteServer.php
  app/Providers/AuthServiceProvider.php
  composer.json
  config/services.php
Labels: dependencies

#181 Add logging for #178 until fixed; add global logging
  .env.example
  app/Http/Controllers/AppealController.php
  app/Jobs/GetBlockDetailsJob.php
  app/MwApi/MwApiExtras.php
  config/logging.php
Labels: enhancement

#156 UTRS ban fixes
  app/Ban.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/AppealController.php
  app/Jobs/GetBlockDetailsJob.php
Labels: Priority: High, bug
