Repository UTRS2/utrs, pull requests merged in 2020-12, with the labels that each got.

#362 November Updates - Round 2
  composer.lock
  package-lock.json
Labels: dependencies

#374 Install the barryvdh/laravel-debugbar package
  composer.json
  composer.lock
  storage/debugbar/.gitignore
Labels: enhancement

#387 Fix appeal corrections when user IP hasn't changed
  app/Http/Controllers/Appeal/PublicAppealModifyController.php
Labels: Priority: High

#379 Fix missed wrong appeal types
  app/Jobs/GetBlockDetailsJob.php
Labels: Priority: High

#372 Remove use of legacy Permission:: methods, cleanup appeal controller
  app/Http/Controllers/AppealController.php
  app/Models/Permission.php
  routes/web.php
Labels: tech-debt

#352 Allow configuring permissions per-wiki
  app/Http/Controllers/Appeal/AppealActionController.php
  app/Http/Controllers/AppealController.php
  app/Models/Permission.php
  app/Models/Privatedata.php
  app/Policies/AppealPolicy.php
  app/Services/MediaWiki/Api/MediaWikiRepository.php
  app/Services/MediaWiki/Api/WikiPermissionHandler.php
  app/Services/MediaWiki/Implementation/RealMediaWikiRepository.php
  app/Services/MediaWiki/Implementation/RealWikiPermissionHandler.php
  config/wikis.php
  database/factories/PrivatedataFactory.php
  resources/views/appeals/appeal.blade.php
  routes/web.php
  tests/Feature/Appeal/Action/ActionAppealCheckUserTest.php
  tests/Feature/Appeal/Action/AppealReserveReleaseTest.php
  tests/Traits/TestHasUsers.php
Labels: enhancement

#383 Improve navbar
  resources/lang/en/home.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: enhancement

#396 Fix commenting
  resources/views/appeals/appeal.blade.php
  routes/web.php
  tests/Feature/Appeal/Action/AppealCommentTest.php
Labels: Priority: High, bug

#388 December 2020 - Round 1 updates
  composer.lock
  package-lock.json
Labels: dependencies
