Repository UTRS2/utrs, pull requests merged in 2021-02, with the labels that each got.

#428 January 2021 updates
  .github/dependabot.yml
  composer.lock
  package-lock.json
  package.json
Labels: dependencies

#406 Drop sendresponses table as it's not needed anymore
  app/Http/Controllers/Appeal/PublicAppealController.php
  app/Http/Controllers/AppealController.php
  app/Models/Sendresponse.php
  database/migrations/2020_03_08_085012_create_send_response.php
  database/migrations/2020_05_25_181741_make_comments_longer.php
  database/migrations/2020_12_13_175450_drop_sendresponses_table.php
Labels: Priority: Low, tech-debt

#400 Remove remains of wikitasks
  app/Http/Controllers/Auth/OauthLoginController.php
  app/Models/Wikitask.php
  database/migrations/2020_12_12_194743_drop_wikitasks_table.php
Labels: tech-debt

#403 Advanced search
  app/Http/Controllers/Appeal/AppealAdvancedSearchController.php
  app/Http/Controllers/Appeal/AppealQuickSearchController.php
  app/Http/Controllers/AppealController.php
  app/Models/Appeal.php
  public/css/app.css
  public/js/app.js
  public/mix-manifest.json
  resources/sass/app.scss
  resources/views/appeals/appeal.blade.php
  resources/views/appeals/appeallist.blade.php
  resources/views/appeals/search/search.blade.php
  resources/views/components/appeal-table.blade.php
  routes/web.php
  tests/Feature/Appeal/Search/AppealAdvancedSearchTest.php
  tests/Feature/Appeal/Search/AppealQuickSearchTest.php
Labels: enhancement

#429 Remove unused import statement
  app/Http/Controllers/Auth/OauthLoginController.php
Labels: bug

#430 Fix requesting CheckUser information
  resources/views/appeals/appeal.blade.php
  routes/web.php
  tests/Feature/Appeal/Action/AppealReferTest.php
Labels: bug

#373 Add database schema and list UI for storing wikis in the database
  app/Console/Commands/ImportWikisFromConfig.php
  app/Http/Controllers/WikiController.php
  app/Models/Wiki.php
  app/Policies/WikiPolicy.php
  app/Providers/AuthServiceProvider.php
  database/factories/WikiFactory.php
  database/migrations/2020_12_05_194341_create_wikis_table.php
  database/migrations/2020_12_05_200000_sync_initial_wikis.php
  database/seeders/DatabaseSeeder.php
  database/seeders/WikiSeed.php
  readme.md
  resources/views/layouts/app.blade.php
  resources/views/wikis/list.blade.php
  routes/web.php
  tests/DuskTestCase.php
  tests/Feature/Appeal/Action/BaseAppealActionTest.php
  tests/Feature/Jobs/WikiPermission/WikiPermissionJobTest.php
  tests/TestCase.php
  tests/Traits/CreatesApplication.php
Labels: enhancement

#289 Move creating appeal table to a Laravel job
  app/Console/Commands/Jobs/UpdateAppealTableOnWikiCommand.php
  app/Console/Kernel.php
  app/Jobs/Scheduled/UpdateWikiAppealListJob.php
  app/Models/Appeal.php
  config/wikis.php
  python/wikiactions.py
  tests/Feature/Jobs/Scheduled/UpdateWikiAppealListJobTest.php
Labels: Priority: Low, enhancement

#433 Fix logging in to MW api
  app/Jobs/Scheduled/UpdateWikiAppealListJob.php
  app/Services/MediaWiki/Api/MediaWikiApi.php
  app/Services/MediaWiki/Implementation/RealMediaWikiApi.php
  tests/Fakes/MediaWiki/FakeMediaWikiApi.php
Labels: bug

#376 Per-wiki templates
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/AppealController.php
  app/Models/Template.php
  app/Models/Wiki.php
  app/Policies/Admin/TemplatePolicy.php
  database/factories/TemplateFactory.php
  database/migrations/2020_12_06_095703_add_wiki_id_to_templates.php
  database/migrations/2020_12_06_100237_backfill_wiki_id_to_templates.php
  database/migrations/2020_12_06_100617_make_wiki_id_non_nullable_in_templates.php
  database/seeders/DatabaseSeeder.php
  database/seeders/WikiSeeder.php
  resources/views/admin/edittemplate.blade.php
  resources/views/admin/newtemplate.blade.php
  tests/Feature/Admin/Templates/TemplateListTest.php
  tests/TestCase.php
  tests/Traits/TestHasUsers.php
Labels: enhancement, merge & testing issues

#431 Feb 2021 Round 1 updates
  app/Jobs/Scheduled/UpdateWikiAppealListJob.php
  composer.json
  composer.lock
  package-lock.json
Labels: dependencies

#439 Feb 2021 Round 2 Updates
  composer.json
  composer.lock
  package-lock.json
Labels: dependencies
